# ---------------------------------------------------------------
#  nav.ejs 首页导航
# ---------------------------------------------------------------
menu:
  回到首页:
    - /
  关于博客:
    - about.html
  友情链接:
    - /PY.html

# ---------------------------------------------------------------
#  nav.ejs  首页归档
# ---------------------------------------------------------------
sides:  
- category #文章分类
- tagcloud #标签
- archive #文章归档
- recent_posts #最新文章

# ---------------------------------------------------------------
#  图片资源
# ---------------------------------------------------------------

favicon: 
  href: /favicon.png # 网站图标
  type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 背景设置
background: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302

# 版权设置
copyright: '<strong>版权声明：</strong>本文采用 <a>CC BY-NC-SA 3.0 CN</a> 协议进行许可'
