# ---------------------------------------------------------------
# ---------------------------------------------------------------
#  配置文件 大纲
#  head.ejs   头部    |  header.ejs 导航栏
#  sidebar.ejs侧边栏   | header.ejs 导航栏
#  footer.ejs jio部   | unit.ejs其他功能插件
#  post.ejs   文章页  |  可能新增配置
#     
# ---------------------------------------------------------------
# ---------------------------------------------------------------



# ---------------------------------------------------------------
#  head.ejs  全局样式 引用的样式和插件
# ---------------------------------------------------------------

# 网站小图标
favicon: 
  href: /favicon.png # 网站图标
  type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)
  
# 阿里 图标库 
aliiconfont: //at.alicdn.com/t/font_1605171_frpek6nqy3j.css

# jq库
jquery:
  js: #https://libs.baidu.com/jquery/2.1.4/jquery.min.js 
    one: /js/jquery1.10.2.min.js
# bootstrap
bootstrap:
  css: /css/bootstrap-3.3.4.css
  js: /js/bootstrap-3.3.4.js
# 头像 css 把这删除头像就不动了
title_qiaoba: /css/avatar_user.css
# slimscroll 滚动条
slimscroll: /js/jquery.slimscroll.min.js
# dearmsdan-post-Statistics样式
Statistics: /css/post_content.css
# dearmsdan-post-Statistics样式
social:
  css: /css/social/social.css
  fontcss: /css/social/waesome.css
# 网站加载条
loadingBar:
  pace: /resources/loadingBar/pace.min.js
  pink: /resources/loadingBar/flash.css
  #pace: https://cdn.bootcss.com/pace/1.0.2/pace.min.js
  #pink: https://cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css
# pjax配置
jquerypjax:
  index: /js/pjax/index.js
  pjax: /js/pjax/jquery.pjax.js
link:
  css: /resources/dearmsdan_link/link.css
# 代码高亮
prettyPrint:
  css: /resources/prettyPrint/css/prettify.css
  js: /resources/prettyPrint/js/prettify.js
# 图片放大功能
preview:
  css: /resources/preview-photo/index.css
  js: /resources/preview-photo/index.js
  min: /resources/preview-photo/preview-photo.js
# valine 评论插件
valine: /js/valine.js

# ---------------------------------------------------------------
#  header.ejs 导航栏
# ---------------------------------------------------------------


dearmsdan:
  logo:  #logo图标设置（设置其中之一就好了
    ico: DearMsDanIconFont icon-zh    #这里将logo设置 图标库ICO
    png: 							  #这里将logo设置图片
    size: 50px # 设置logo大小
  title: 
    size: 20px # 设置网站名字大小

# 顶部
menu:
  首页:
    - /
  关于:
    - about.html
  评论区:
    - /valine.html
  友情链接:
    - /link.html
  
  
# ---------------------------------------------------------------
#  sidebar.ejs 侧边栏
# ---------------------------------------------------------------


# 您可以选择视频 或者 图片设置为头像（＞▽＜）
#  适合窄长视频 和 同比例图片
# 样式在source/css/style.css 中 741,731行 左右
# （设置其中一个的值即可）设置图片不动的配置在title_qiaoba中
PhotoHead: /resources/qiaoba.png
VideoHead: /Pexels.mp4

# 社交按钮配置
socialbtn:
  GitHub:
    - https://github.com/ZHD99/
    - icon-git
  email:
    - mailto:dearmsdan@outlook.com
    - icon-youxiang
  netease:
    - https://music.163.com/
    - icon-netease
  qq:
    - https://wpa.qq.com/msgrd?v=3&uin=2646405301&site=qq&menu=yes
    - icon-qq
  weibo:
    - https://weibo.com/
    - icon-weibo
	
# 可自定义目录，具体添加在sidebar.ejs 59行
Catalog:
  自定义目录:
    - /
Catalog_son:
  地址0...:
    - /链接
  地址1...:
    - /链接
  地址2...:
    - /链接
  地址3...:
    - /链接


sides:  
- category #文章分类
- tagcloud #标签
- archive #文章归档
- recent_posts #最新文章


# 搜索插件
# 请安装 ↓ 插件才能使用全文搜索
# npm install hexo-generator-search  --save
# npm install hexo-generator-searchdb --save
searchbtn: /js/s.js



# ---------------------------------------------------------------
#  unit.ejs 新增无影响其他功能插件
# ---------------------------------------------------------------

# 音乐播放器
player:
  audio:
    css: /resources/meuplayer/css/player.css
    js: 
      index: /resources/meuplayer/player/index.js
      player: /resources/meuplayer/player/player.js
      playlist: /resources/meuplayer/player/playlist.js
      player_database: /resources/meuplayer/player/player_database.js
# 返回顶部
top:
  js: /js/top/jquery.toTop.min.js


# ---------------------------------------------------------------
#  footer.ejs  jio部的配置
# ---------------------------------------------------------------


# footer 时间统计
jscex:
  jsq: /resources/jscex/jscex.min.js             # 必须
  jsa: /resources/jscex/jscex-parser.js          # 必须
  jsz: /resources/jscex/jscex-jit.js             # 必须
  jsw: /resources/jscex/jscex-builderbase.min.js # 必须
  jss: /resources/jscex/jscex-async.min.js       # 必须
  jsx: /resources/jscex/jscex-async-powerpack.min.js

# footer 版权和一些信息
footer:
  # text 和 beian 信息都可以删除
  text: "感谢<a style='color: #00bbff;font-weight: bolder;' href='https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral'>又拍云</a> 提供强力云存储服务 |  <a style='color:#f66464;font-weight: bolder;' href='https://www.dnspod.cn/'>dnspod </a>提供 DNS 解析服务|  <a style='color:#ea9000;font-weight: bolder;' href='https://valine.js.org/'> Valine</a>提供快速、简洁且高效的评论系统 <br/>"
  
  beian: "<a style='color:#939393;' href='http://hn.beian.miit.gov.cn/' target='_blank'> <img width='16px' src='https://img.alicdn.com/tfs/TB1..50QpXXXXX7XpXXXXXXXXXX-40-40.png' />湘ICP备20001824号 </a>， <a target='_blank' href='http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=43010302001049' style='display:inline-block;text-decoration:none;height:20px;line-height:20px;'><p style='height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;'>湘公网安备 43010302001049号</p></a>"

# footer 页jio的时间
# 时间年月日，注意月份是0-11 !!
  time: 
    year: 2019
    m: 11
    d: 25



# ---------------------------------------------------------------
#  post.ejs 
# ---------------------------------------------------------------

# 可能是文章自动生成目录及侧边栏目录滚动特效的插件toc-helper
tochelper:
  css: /resources/tochelper/toc-helper.min.css
  js: /resources/tochelper/toc-helper.min.js

# 页脚  版权设置
copyright: '<strong>版权声明：</strong>本文采用 <a>....</a> 协议进行许可'







# ---------------------------------------------------------------
#  **.ejs  可能添加的配置信息
# ---------------------------------------------------------------

# 背景设置
background: https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302

